services:
  bot:
    image: ghcr.io/anasxonummataliy/english-vocab:latest
    container_name: english_vocab
    env_file:
      - .env
    ports:
      - "8000:8007"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000


