services:
  bot:
    image: ghcr.io/anasxonummataliy/english-vocab:latest
    container_name: english_vocab
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: english_vocab_db
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - app-network
  redis:
    image: redis:7-alpine
    container_name: english_vocab_redis
    restart: always
    networks:
      - app-network
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:


networks:
  app-network:
    driver: bridge
